== Introducción

En este trabajo practico modelaremos transacciones de tarjetas de credito para ello, debemos crear una base de datos e instanciar todos los datos de clientes, tarjetas y comercios. 

Por otro lado, para controlar que las compras sean validas, creamos Stored Procedures y Triggers. Finalizando con la creacion de una base de datos NoSQL basada en JSON. 

== Descripción

En el curso de la resolucion del trabajo practico nos encontramos con varias dificultades que supimos resolver: 

* Sintaxis del lenguaje : Acostumbrados a otro tipo de lenguaje mas flexible en donde la sintaxis no ocupaba un rol muy importante, con Go supimos padecer esta mala praxis. 

* Errores en SQL : no sabiamos que errores tiraba psql pq decia que el error estaba "cerca" o a veces no era ni lo q marcaba. Solucion : comando cat var/log/postgres/postgresql-12-main.log que nos daba un historial de errores en donde los detallaba mas

* Interpretacion de la consigna : muchos veces hicimos codigo de mas o pensamos en cosas, quizas mas dificiles en resolver por lo que tardabamos mucho tiempo en hacerlas, y al final eran cosas mas faciles

* Triggers : se nos resulto complejo comprender el uso adecuado del Before y After en cada situacion, ademas de que en un principio no comprendiamos del todo como funcionaba  pero revisando las clases y la documentacion pudimos entenderlo un poco mejor


Como desicion de diseño importante en cuanto al codigo, viendo que este se hacia muy extenso, fue que se decidio separalo en varios archivos .sql y  en el archivo .go solo los ejecutabamos. 


DESCRIPCION GENERAL :


== Implementación

Para cargar la base de datos y sus tablas guardamos los comandos necesarios para esto en archivos .sql y que son ejecutados mediante un funcion de go llamada "crearBase()" y "cargaDatos()".  


En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

