alter table cliente add constraint cliente_pk primary key (nro_cliente);
alter table comercio add constraint comercio_pk primary key (nro_comercio);
alter table tarjeta add constraint tarjeta_pk primary key (nro_tarjeta);
alter table compra add constraint compra_pk primary key (nro_operacion);
alter table rechazo add constraint rechazo_pk primary key (nro_rechazo);
alter table cierre add constraint cierre_pk primary key (año,mes,terminacion);
alter table cabecera add constraint cabecera_pk primary key (nro_resumen);
alter table detalle add constraint detalle_pk primary key (nro_resumen,nro_linea);
alter table alerta add constraint alerta_pk primary key (nro_alerta)
